### ISSUE TITLE
build offline registry error

### ISSUE THREAD

**Issue by spring-bu** [eclipse-che/che-plugin-registry#847]
OS: centos7
node: 12.20.2
yarn: v1

![image](https://user-images.githubusercontent.com/37682426/108662159-ad24f280-7508-11eb-95c6-0e630b68b2b1.png)

**Comment by ibuziuk** [comment]
@spring-bu please open an issue in the https://github.com/eclipse/che/issues (all the plugin registry-related issues are tracked there)
