### ISSUE TITLE
Unable to do local build of che-plugin-registry

### ISSUE THREAD

**Issue by chaitu454** [eclipse-che/che-plugin-registry#936]
I am trying to build che-plugin-registry from 7.28.X branch.  For instance I am not changing anything just trying to build as-is and i am getting error as  either of below errors. 

I can see that the plugin is downloadable from browser and it does have package.json. So what can be the issue here.

stack=Error: end of central directory record signature not found

or

UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/tmp/che-plugin-registry/unpack-folder/vscode.typescript-language-features-1.49.3.vsix/extension/package.json'

**Comment by ericwill** [comment]
Hello, please file this issue in the [main repo](https://github.com/eclipse/che/issues). This one is only used for PRs/code.

**Comment by chaitu454** [comment]
Issue resolved but clearing /tmp/che-plugin-registry/
